name: webview_universal
description: Show a webview window on your flutter desktop application.
version: 0.0.0

platforms:
  android:
  ios:
  linux:
  macos:
  windows:
  web:
  
environment:
  sdk: ">=2.14.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  path: ^1.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
 
flutter:
  plugin:
    platforms:
      macos:
        pluginClass: WebviewUniversalPlugin
      windows:
        pluginClass: WebviewUniversalPlugin
      linux:
        pluginClass: WebviewUniversalPlugin
